snyk auth token added

diff --git a/.github/workflows/devsecops-workflow.yaml b/.github/workflows/devsecops-workflow.yaml
--- a/.github/workflows/devsecops-workflow.yaml
+++ b/.github/workflows/devsecops-workflow.yaml
@@ -56,44 +56,44 @@ jobs:
   #         args: --sarif-file-output=snyk.sarif
   #         command: test
 
-  component-analysis:
-    name: ComponentAnalysis-Node-NPMAudit
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout the Code
-        uses: actions/checkout@v3
+  # component-analysis:
+  #   name: ComponentAnalysis-Node-NPMAudit
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout the Code
+  #       uses: actions/checkout@v3
 
-      - name: Setup Node.js 18
-        uses: actions/setup-node@v3
-        with:
-          node-version: '18'
+  #     - name: Setup Node.js 18
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '18'
 
-      - name: Install the Libraries or Node Modules
-        run: npm install
+  #     - name: Install the Libraries or Node Modules
+  #       run: npm install
 
-      # - name: Perform Node.js Audit and Output to Json file
-      #   run: npm audit --json >> node-audit-results.json
-      #   continue-on-error: true
+  #     # - name: Perform Node.js Audit and Output to Json file
+  #     #   run: npm audit --json >> node-audit-results.json
+  #     #   continue-on-error: true
 
-      - name: Perform Node.js Audit and Output to Json file
-        run: |
-          npm audit --json >> node-audit-results.json
-          if [ $? -eq 0 ]; then
-            echo "npm audit completed successfully"
-          else
-            echo "npm audit failed with exit code $?"
-          fi
-        continue-on-error: true
+  #     - name: Perform Node.js Audit and Output to Json file
+  #       run: |
+  #         npm audit --json >> node-audit-results.json
+  #         if [ $? -eq 0 ]; then
+  #           echo "npm audit completed successfully"
+  #         else
+  #           echo "npm audit failed with exit code $?"
+  #         fi
+  #       continue-on-error: true
 
-      - name: List the files available
-        run: ls
+  #     - name: List the files available
+  #       run: ls
       
-      - name: Upload the Output as an artifact
-        uses: actions/upload-artifact@v3.1.1
-        with:
-          name: NodeAudit Output
-          path: node-audit-results.json
-        if: always()
+  #     - name: Upload the Output as an artifact
+  #       uses: actions/upload-artifact@v3.1.1
+  #       with:
+  #         name: NodeAudit Output
+  #         path: node-audit-results.json
+  #       if: always()
 
   oast-frontend-retirejs:
     name: SAST-Frontend-Job-NodeJS-RetireJS
@@ -110,8 +110,8 @@ jobs:
       - name: Install the Libraries or Node Modules
         run: npm install
 
-      - name: Perform RetireJS Scan
-        run: npx retire --outputformat json >> retirejs-results.json
+      - name: Run RetireJS using docker image
+        run: docker run --rm -v $(pwd):/src -w /src hysnsec/retire --outputformat json --outputpath retirejs-report.json --severity high
         continue-on-error: true
 
       - name: List the files available
@@ -121,7 +121,7 @@ jobs:
         uses: actions/upload-artifact@v3.1.1
         with:
           name: RetireJS Output
-          path: retirejs-results.json
+          path: retirejs-report.json
         if: always()
 
   oast-snyk:
@@ -146,7 +146,9 @@ jobs:
         run: npm install
 
       - name: Run Snyk
-        run: snyk test --json > snyk-results.json
+        run: |
+          snyk auth $SNYK_TOKEN
+          snyk test --json > snyk-results.json
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         continue-on-error: true
